plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

# SEO Stuff
name: Balkanology - Explore Southeast Europe
title: Balkanology - Explore Southeast Europe
author: Alan Grant
description: A guide to travel in the countries of the Balkan Peninsula
lang: en
locale: en_GB
url: "https://balkanology.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20

defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      permalink: /blog/:slug/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

relative_links:
  enabled: true
  collections: true